save_path = "snr_ser/direct/12.5/debug";
save_path_mat = save_path+"/amp"+amp+"/mat";
%%
load(save_path_mat+"/save_data.mat");
load(save_path_mat+"/save_data_inf.mat");
load(save_path_mat+"/save_data_beforecorrect.mat");
load(save_path_mat+"/save_data_forcorrect.mat");
load(save_path_mat+"/save_data_aftercorrect.mat");
load(save_path_mat+"/save_signal_send.mat");
load(save_path_mat+"/save_signal_ori.mat");
load(save_path_mat+"/save_signal_send_inf.mat");
load(save_path_mat+"/save_signal_pass_channel_inf.mat");
load(save_path_mat+"/save_signal_pass_channel.mat");
load(save_path_mat+"/save_signal_pass_channel_correct.mat");
load(save_path_mat+"/save_signal_received_inf.mat");
load(save_path_mat+"/save_fin_syn_point_inf.mat");
load(save_path_mat+"/save_coar_syn_point_inf.mat");
load(save_path_mat+"/save_signal_received_real_send1.mat");
load(save_path_mat+"/save_fin_syn_point_real_send1.mat");
load(save_path_mat+"/save_coar_syn_point_real_send1.mat");
load(save_path_mat+"/save_signal_received_real_send2.mat");
load(save_path_mat+"/save_fin_syn_point_forcorrect.mat");
load(save_path_mat+"/save_coar_syn_point_real_send2.mat");
load(save_path_mat+"/save_signal_received_aftercorrect.mat");
load(save_path_mat+"/save_replace_location.mat");
load(save_path_mat+"/save_errlocation_before.mat");
load(save_path_mat+"/save_errlocation_forcorrect.mat");
load(save_path_mat+"/save_errlocation_after.mat");
%%
save_data_demod_nofalse = ['save_data_' num2str(looptime)];
save_data_demod_inf = ['save_data_inf_' num2str(looptime)];
save_data_demod_notcorrect = ['save_data_beforecorrect_' num2str(looptime)];
save_data_demod_forcorrect = ['save_data_forcorrect_' num2str(looptime)];
save_data_demod_aftercorrect = ['save_data_aftercorrect_' num2str(looptime)]; 
save_signal_send = ['save_signal_send_' num2str(looptime)];
save_signal_ori = ['save_signal_ori_' num2str(looptime)];
save_signal_send_inf = ['save_signal_send_inf_' num2str(looptime)];
save_signal_pass_channel_inf = ['save_signal_pass_channel_inf_' num2str(looptime)];
save_signal_pass_channel = ['save_signal_pass_channel_' num2str(looptime)];
save_signal_pass_channel_correct = ['save_signal_pass_channel_correct_' num2str(looptime)];
save_signal_received_inf = ['save_signal_received_inf_' num2str(looptime)];
save_fin_syn_point_inf = ['save_fin_syn_point_inf_' num2str(looptime)];
save_coar_syn_point_inf = ['save_coar_syn_point_inf_' num2str(looptime)];
save_signal_received_real_send1 = ['save_signal_received_real_send1_' num2str(looptime)];
save_fin_syn_point_real_send1 = ['save_fin_syn_point_real_send1_' num2str(looptime)];
save_coar_syn_point_real_send1 = ['save_coar_syn_point_real_send1_' num2str(looptime)];
save_signal_received_real_send2 = ['save_signal_received_real_send2_' num2str(looptime)];
save_fin_syn_point_forcorrect = ['save_fin_syn_point_forcorrect_' num2str(looptime)];
save_coar_syn_point_real_send2 = ['save_coar_syn_point_real_send2_' num2str(looptime)];
save_signal_received_aftercorrect = ['save_signal_received_aftercorrect_' num2str(looptime)];
save_replace_location = ['save_replace_location_' num2str(looptime)];
save_errlocation_before = ['save_errlocation_before_' num2str(looptime)];
save_errlocation_forcorrect = ['save_errlocation_forcorrect_' num2str(looptime)];
save_errlocation_after = ['save_errlocation_after_' num2str(looptime)];
%%
data_demod_nofalse = eval(save_data_demod_nofalse);
data_demod_inf = eval(save_data_demod_inf);
data_demod_notcorrect = eval(save_data_demod_notcorrect);
data_demod_forcorrect = eval(save_data_demod_forcorrect);
data_demod_aftercorrect = eval(save_data_demod_aftercorrect);
signal_send = eval(save_signal_send);
signal_ori = eval(save_signal_ori);
signal_send_inf = eval(save_signal_send_inf);
signal_pass_channel_inf = eval(save_signal_pass_channel_inf);
signal_pass_channel = eval(save_signal_pass_channel);
signal_pass_channel_correct = eval(save_signal_pass_channel_correct);
signal_received_inf = eval(save_signal_received_inf);
fin_syn_point_inf = eval(save_fin_syn_point_inf);
coar_syn_point_inf = eval(save_coar_syn_point_inf);
signal_received_notcorrect = eval(save_signal_received_real_send1);
fin_syn_point = eval(save_fin_syn_point_real_send1);
coar_syn_point = eval(save_coar_syn_point_real_send1);
signal_received_forcorrect = eval(save_signal_received_real_send2);
fin_syn_point_forcorrect = eval(save_fin_syn_point_forcorrect);
coar_syn_point_forcorrect = eval(save_coar_syn_point_real_send2);
signal_received_aftercorrect = eval(save_signal_received_aftercorrect);
replace_location = eval(save_replace_location);
errlocation_before = eval(save_errlocation_before);
errlocation_forcorrect = eval(save_errlocation_forcorrect);
errlocation_after = eval(save_errlocation_after);

